paths:
  input_filepath: data/processed
  figures_filepath: reports/figures
  model_filepath: models

image:
  size: 180
  channels: 3

model:
  lr: 1e-4
  batch_size: 32
  dropout: 0.2
  classes: 2

conv_layers:
  - out_channels: 16
    kernel_size: 3
    stride: 1
    padding: 1
    
  - out_channels: 32
    kernel_size: 3
    stride: 1
    padding: 1

maxpool:
  kernel_size: 3
  stride: 1
  padding: 1

HYDRA_FULL_ERROR: 1