paths:
  input_filepath: data/processed
  figures_filepath: reports/figures
  model_filepath: models

image:
  size: 180
  channels: 3

model:
  lr: 1e-4
  batch_size: 32
  dropout: 0.2
  classes: 2

conv_layers:
  - out_channels: 64
    kernel_size: 3
    stride: 1
    padding: 1
<<<<<<< HEAD
    
  - out_channels: 128
    kernel_size: 3
    stride: 1
    padding: 1
linear_layer:
  output: 512
=======
>>>>>>> 60072233c253b5b2b2801126d56d1919b34f78f9

maxpool:
  kernel_size: 2
  stride: 2
  padding: 1

HYDRA_FULL_ERROR: 1